import = ['~/.config/alacritty/themes/blood_moon.toml']

[env]
TERM = "xterm-256color"

[window]
startup_mode = "SimpleFullscreen"
opacity = 0.60
title = "term"
dynamic_title = false
option_as_alt = "Both"

[font]
size = 16
normal = { family = "GohuFont 14 Nerd Font" }

[mouse]
hide_when_typing = true
